### ISSUE TITLE
Old version from Feb 6 works new one crashing

### ISSUE THREAD

**Issue by River-b** [pine64/pine64_updater#28]
Good News:
just discovered that this older Updater given to me on Feb 6, 2022 still works perfectly for any language selected
     https://discord.com/channels/463237927984693259/769635442969542676/939858275367780422

Bad news
Only the latest release in Github is crashing in windows for all languages, but custom local installs works with the app.

Other differences I noticed:
     *working version has 2.16 English as first language.
     *broken latest version is fetching github list that is not ordered

Are they both fetching from Gitub differently  -perhaps handling is possible problem?  how did Feb 6 version I got get list since it is definitely in a different order.

tested older linked version at least 10 times now, no crashes at all on any language I select.  something changed from that one to new one.

Separately, MarkBigTex  tried  2 versions on a MAC today and is getting only white blank screen.

**Comment by River-b** [comment]
Interesting Updater results now  (reason I thought that the new updater magically fixed is that is working for some languages) 
This is testing only on latest Github version, please forgive the spelling, I can't do the accents.
  *Languages that Work and do not crash - tested several times with these languages:
         ** Deutch , Romana, Cpnckn, Netherlands, Dansk, Magyar
  * Languages that always crash:  English, Lietuviu, Italian , Chinese , Slovencina , YkpaiHCbKA, Norsk , Hrvatski, Suomi
ALso, they are crashing at different points in download.
I had to stop testing more languages because now the Dropdown won't show anything from Github [5:55 PM] PST time California.   all I get is Custom, no dropdown list at all.

At 5:57pm, now github list is back. .... something weird happening, Github list disappeared not accesible from Updater, and now it's back.

**Comment by River-b** [comment]
To compare, I tested a bunch of languages in older version i received on Feb. 6 and they all work no crash or issue.
I did not test every language, but that was enough for me to believe the older version is working well. 
confirmed good tests:  
english, europe multi, chinese + japanese, bulgarian/russian/serbian/ukranian multi, belarus, czech , german, french, spanish

**Comment by gamelaster** [comment]
Thanks for reporting, this happens because of bug mentioned #27 .
