### ISSUE TITLE
Windows v1.03 zip file is still v1.02

### ISSUE THREAD

**Issue by ytsejam1138** [pine64/pine64_updater#35]
Downloaded v1.03, but when I run the program it prompts me to update to a new version.  Looking under About it shows that it's v1.02

**Comment by gamelaster** [comment]
Oh, good notice, weird, probably because I didn't updated Windows .rc file. Will fix it, thanks.

**Comment by janowakps** [comment]
still is 1.02

**Comment by dmitrygribenchuk** [comment]
still is 1.02

**Comment by gamelaster** [comment]
Should be fixed now.
