### ISSUE TITLE
Request for video showing 24 volt hardware modification

### ISSUE THREAD

**Issue by pgiacalo** [pine64/pine64_updater#38]
Could someone on your expert team please make a short Youtube video showing exactly how to modify the Pinecil to support 24 volts? I have searched the internet and have not been able to find a clear, explicit explanation. Since making such hardware changes could potentially ruin the Pinecil, it's important to know _exactly_ how to do it. A short, clear video is worth a thousand words and would greatly reduce the chance of errors. 

Also, when is Pinecil planning to modify the device design so that they ship with the 24 volt hardware modification? 

Thank you.

**Comment by gamelaster** [comment]
Hello, the PINE64 is a community, doing all those software and all other things around for example Pinecil, in their free time.
So we all are volunteers. About the 24 Volt modification, you probably mean VBUS mod, and there are several tutorials about them. Best will be ask on PINE64 Pinecil channels, you can find them on the wiki here: https://wiki.pine64.org/wiki/Main_Page . Thanks
