### ISSUE TITLE
Question about current limit protection

### ISSUE THREAD

**Issue by pgiacalo** [pine64/pine64_updater#39]
Does turning on the current limit protect the Pinecil, if it is accidentally connected to 24 volts? I have set my Pinecil current limit to 60 amps and wonder if that will protect it from such accidental damage. Thanks.

**Comment by gamelaster** [comment]
@pgiacalo Sorry, I don't know, please ask those questions in #pinecil chats (on Telegram, Discord, IRC or Matrix), you can find links here: https://wiki.pine64.org/wiki/Main_Page , Thanks.
