### ISSUE TITLE
Updater crashed after erasing: pincil is now briked

### ISSUE THREAD

**Issue by mcenderdragon** [pine64/pine64_updater#45]
I tried to update my pincil becuase USB PD doent work at all, I got it very early so in IronOS it might be fixed. but after multiple attempts Updated shortly displaed erasing and then closed itself. the Pincil is now unresponsive so guess it erased the old firmware btu never flashed the new firmware.

I am usibng win 10. is there any log folder where all log is written to? the log in the updater itself is displayed only for a split seccond befor it all crashes and is gone.

**Comment by gamelaster** [comment]
Use dfu-util manually: https://wiki.pine64.org/wiki/Pinecil#Update_Pinecil_V1

**Comment by mcenderdragon** [comment]
```
PS C:\Users\Max\Downloads\dfu-util-0.11-binaries\dfu-util-0.11-binaries\win64> .\dfu-util.exe -D .\Pinecil_EN.dfu
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 28e9
Match product ID from file: 0189
Failed to retrieve language identifiers
Broken LANGID string descriptor
Failed to retrieve string descriptor 6
Failed to retrieve string descriptor 3
Multiple alternate interfaces for DfuSe file
Opening DFU capable USB device...
Device ID 28e9:0189
Device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Interface #1 ...
Determining device status...
error get_status: LIBUSB_ERROR_PIPE
PS C:\Users\Max\Downloads\dfu-util-0.11-binaries\dfu-util-0.11-binaries\win64> .\dfu-util.exe -D .\Pinecil_EN.dfu
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 28e9
Match product ID from file: 0189
Cannot open DFU device 28e9:0189 found on devnum 78 (LIBUSB_ERROR_NOT_SUPPORTED)
No DFU capable USB device available
PS C:\Users\Max\Downloads\dfu-util-0.11-binaries\dfu-util-0.11-binaries\win64> .\dfu-util.exe -D .\Pinecil_EN.dfu
```
ALso failed sadly. the device is connected as the unknown usb device is in the device manager

**Comment by gamelaster** [comment]
Follow this instruction:
https://ralim.github.io/IronOS/Flashing/Pinecil%20V1/
**Option 2: use the GUI tool from chip vendor**

**Comment by mcenderdragon** [comment]
> Follow this instruction: https://ralim.github.io/IronOS/Flashing/Pinecil%20V1/ **Option 2: use the GUI tool from chip vendor**

thanks for the reply, the drivers are availabel but it donet find the tool anymore

**Comment by mcenderdragon** [comment]
i am trying the GD32 AllInOne Programmerv2.1.8.15043. and so far is succefully conntected but eraing is making no progress at all, so dunno if it crashed silently

**Comment by mcenderdragon** [comment]
the All In One Programmer also doenst help, I think becuase its to new or soemthing. I tried to clear the driver and installed it again and resarted the whole system and the resuklted in the following error:

```
PS C:\Users\Max\Downloads\dfu-util-0.11-binaries\dfu-util-0.11-binaries\win64> .\dfu-util.exe -D .\Pinecil_EN.dfu
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 28e9
Match product ID from file: 0189
Multiple alternate interfaces for DfuSe file
Opening DFU capable USB device...
Device ID 28e9:0189
Device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Interface #1 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Option Bytes  "
DfuSe interface name: "Internal Flash  "
Found GD32VF103, which reports a bad page size and count for its internal memory.
Fixed layout based on part number: page size 1024, count 128.
File contains 1 DFU images
Parsing DFU image 1
Target name: ST...
Image for alternate setting 0, (1 elements, total size = 53804)
Setting Alternate Interface #0 ...
Parsing element 1, address = 0x08000000, size = 53796
Erase           [                         ]   0%            0 bytesERASE_PAGE not correctly executed
```
So erase has failed

**Comment by River-b** [comment]
@mcenderdragon 

1. try [Pineflash GUI App](https://github.com/Spagett1/PineFlash)  if you have Linux or Mac.  It's usually not possible to brick a Pinecil with a firmware update, we just write over it again, even if the screen went black, it's possible. unless something else is wrong with it.

could you provide some back ground info on it?

1. about how long ago did you buy  the V1?
2. which website is it from?
3. what color is the handle and the rubber finger grip?

Follow instructions on this pinecil wiki page:
https://wiki.pine64.org/wiki/Pinecil#Firmware_&_Updates
if none of those instructions work, then join the live pinecil volunteer chat channel, links to it in that wiki.

**Comment by mcenderdragon** [comment]
> @mcenderdragon
> 
>     1. try [Pineflash GUI App](https://github.com/Spagett1/PineFlash)  if you have Linux or Mac.  It's usually not possible to brick a Pinecil with a firmware update, we just write over it again, even if the screen went black, it's possible. unless something else is wrong with it.
>

I have a windos and tried it multiple times, the origramm jsut closes. and the CMD tool always hangs at the erasing, is it possible to jsut overwrite without erasing ?

> 
> could you provide some background info on it?
> 
>     1. about how long ago did you buy  the V1?
>

January 2021

>     2. which website is it from?

The official pine64 webside; So the pine Store

>     3. what color is the handle and the rubber finger grip?
> 

Handle is black, and the rubber is a light blue

> Follow instructions on this pinecil wiki page: https://wiki.pine64.org/wiki/Pinecil_Firmware if none of those instructions work, then join the live pinecil volunteer chat channel, links to it in pinecil wiki also

ok I will try

**Comment by River-b** [comment]
Here is the user manual for the pinecil V1. 
the minimum voltage from the manufacturer is 12V -21V and 3 amps.  9v is not in the spec. Look at the side of the pinecil v1 handle, it will also have the printed voltage range of 12V - 21V.
https://wiki.pine64.org/images/1/1f/USER_MANUAL_-_QUICK_START_PINECIL_multi_lang_EU%2BDE%2BFR.pdf

technically there is an end-user modification that could be done on some of these older ones to allow them to safely do up to 24V for higher performance.
