### ISSUE TITLE
DFU-Util exited with error code 6 on MacOS 11.1

### ISSUE THREAD

**Issue by athisun** [pine64/pine64_updater#6]
The dfu-util bundled in the macOS package seems to be broken, referencing a dyld library specific to a development machine.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/7977719/106293859-32b2db00-629a-11eb-9960-189fa741a86d.png">

```
dyld: Library not loaded: /Users/gamiee/Desktop/libusb-1.0.24/../build/lib/libusb-1.0.0.dylib Referenced from: /Users/acarr/Desktop/pinecil_firmware_updater.app/Contents/MacOS/dfu-util Reason: Incompatible library version: dfu-util requires version 4.0.0 or later, but libusb-1.0.0.dylib provides version 2.0.0 
DFU-Util exited with error code 6!
Flashing failed.
```

I found that replacing the bundled dfu-util with one from Homebrew worked a treat, with only one warning appearing immediately after the dfu-util copyright information. 

```
dfu-util: Warning: Invalid DFU suffix signature dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
```

<img width="719" alt="image" src="https://user-images.githubusercontent.com/7977719/106294798-56c2ec00-629b-11eb-87b1-b79e03ffb020.png">

Instructions:
1. Right-click the pinecil_firmware_updater.app package
2. Select "Show Package Contents"
3. Navigate to "pinecil_firmware_updater.app/Contents/MacOS" 
4. Delete (or rename) the broken `dfu-util` file
5. Install dfu-util using Homebrew `brew install dfu-util`
6. Find the install location `brew info dfu-util`, mine was `/usr/local/Cellar/dfu-util/0.10/bin`
7. Copy dfu-util to "pinecil_firmware_updater.app/Contents/MacOS"

**Comment by gamelaster** [comment]
Hello, thanks for reporting.
> The dfu-util bundled in the macOS package seems to be broken, referencing a dyld library specific to a development machine.

This is weird. @OndroNR was testing the v1.1 and it worked finely for him, so that's weird. Maybe I forget to add correct dylib into the same folder with dfu-util. Will check it.

> I found that replacing the bundled dfu-util with one from Homebrew worked a treat, with only one warning appearing immediately after the dfu-util copyright information.

This is okay, happens also on bundled dfu-util.

The reason why dfu-util is packaged inside is that application should be make the job without installing anything or requiring having homebrew.

**Comment by OndroNR** [comment]
Hi, I tested it on macOS Mojave. I have not yet upgraded to Catalina or Big
Sur.

**Comment by RKosbab** [comment]
I ran into the same issue athisun did initially (Same message and everything) and followed his steps to correct the issue. This happened on MacOS 11.3. 

On the plus side, i did not get the same DFU suffix message that they got.

**Comment by Grippy98** [comment]
This issue is also present on M1 Macs running MacOS 11.3.1 (Latest)

@athisun 's replacement from brew also worked for me. 

My path was /opt/homebrew/Cellar/dfu-util/0.10 , so others can also expect similar. But find your own like he said with "brew info". 

Thanks for the help.

**Comment by phlebas** [comment]
Is there any update for this issue? I still can't update firmware on my Pinecil.

**Comment by Grippy98** [comment]
> Is there any update for this issue? I still can't update firmware on my Pinecil.

Yes, just replace the bundled dfu-util as the top reply on this thread suggests and it works fine.

**Comment by andypiper** [comment]
I'm seeing the same thing on my M1 Pro. Resolved via

`ln -s `which dfu-util` /Users/andypiper/Downloads/pinecil_firmware_updater.app/Contents/MacOS`

**Comment by gamelaster** [comment]
Hmm, I think the dfu-util still should be bundled inside the application (since not everyone have brew installed), although, it would be good to also have option to use system-installed dfu-util in case the integrated one doesn't work, so I'm thinking about adding an option in settings for this.

**Comment by tormodvolden** [comment]
Yes, also because people without brew might install the macOS binaries from dfu-util.sourceforge.net.

**Comment by athisun** [comment]
Confirmed fixed. 👍  Thanks @gamelaster
